package com.slack.ecotown.model.view;

// Generated 30/12/2017 12:09:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewTerceroResiduo generated by hbm2java
 */
@Entity
@Table(name = "view_tercero_residuo", schema = "public")
public class ViewTerceroResiduo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ViewTerceroResiduoId id;

	public ViewTerceroResiduo() {
	}

	public ViewTerceroResiduo(ViewTerceroResiduoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "intpkres", column = @Column(name = "intpkres")),
			@AttributeOverride(name = "strdscrpcn", column = @Column(name = "strdscrpcn", length = 150)),
			@AttributeOverride(name = "strorgnrsdo", column = @Column(name = "strorgnrsdo", length = 150)),
			@AttributeOverride(name = "strcmntro", column = @Column(name = "strcmntro", length = 150)),
			@AttributeOverride(name = "strdrccn", column = @Column(name = "strdrccn", length = 100)),
			@AttributeOverride(name = "numcntdd", column = @Column(name = "numcntdd", precision = 20)),
			@AttributeOverride(name = "strprsntcn", column = @Column(name = "strprsntcn", length = 300)),
			@AttributeOverride(name = "booldnr", column = @Column(name = "booldnr")),
			@AttributeOverride(name = "numprco", column = @Column(name = "numprco", precision = 20)),
			@AttributeOverride(name = "intpkter", column = @Column(name = "intpkter")),
			@AttributeOverride(name = "intrptcn", column = @Column(name = "intrptcn")),
			@AttributeOverride(name = "strmncpo", column = @Column(name = "strmncpo", length = 100)),
			@AttributeOverride(name = "boolactvo", column = @Column(name = "boolactvo")),
			@AttributeOverride(name = "tmastrnmbre", column = @Column(name = "tmastrnmbre", length = 100)),
			@AttributeOverride(name = "tmestrnmbre", column = @Column(name = "tmestrnmbre", length = 50)) ,
			@AttributeOverride(name = "stricno", column = @Column(name = "stricno", length = 100))})
	public ViewTerceroResiduoId getId() {
		return this.id;
	}

	public void setId(ViewTerceroResiduoId id) {
		this.id = id;
	}

}
