package com.slack.ecotown.model.view;

// Generated 30/12/2017 12:09:35 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewTerceroResiduoId generated by hbm2java
 */
@Embeddable
public class ViewTerceroResiduoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer intpkres;
	private String strdscrpcn;
	private String strorgnrsdo;
	private String strcmntro;
	private String strdrccn;
	private BigDecimal numcntdd;
	private String strprsntcn;
	private Boolean booldnr;
	private BigDecimal numprco;
	private Integer intpkter;
	private String strmncpo;
	private Boolean boolactvo;
	private String tmastrnmbre;
	private String tmestrnmbre;
	private String stricno;
	private Integer intrptcn;

	public ViewTerceroResiduoId() {
	}

	public ViewTerceroResiduoId(Integer intpkres, String strdscrpcn, String strorgnrsdo, String strcmntro, String strdrccn, BigDecimal numcntdd,
			String strprsntcn, Boolean booldnr, BigDecimal numprco, Integer intpkter, String strmncpo, Boolean boolactvo, String tmastrnmbre,
			String tmestrnmbre, String stricno, Integer intrptcn) {
		this.intpkres = intpkres;
		this.strdscrpcn = strdscrpcn;
		this.strorgnrsdo = strorgnrsdo;
		this.strcmntro = strcmntro;
		this.strdrccn = strdrccn;
		this.numcntdd = numcntdd;
		this.strprsntcn = strprsntcn;
		this.booldnr = booldnr;
		this.numprco = numprco;
		this.intpkter = intpkter;
		this.strmncpo = strmncpo;
		this.boolactvo = boolactvo;
		this.tmastrnmbre = tmastrnmbre;
		this.tmestrnmbre = tmestrnmbre;
		this.stricno = stricno;
		this.intrptcn = intrptcn;
	}

	@Column(name = "intpkres")
	public Integer getIntpkres() {
		return this.intpkres;
	}

	public void setIntpkres(Integer intpkres) {
		this.intpkres = intpkres;
	}

	@Column(name = "strdscrpcn", length = 150)
	public String getStrdscrpcn() {
		return this.strdscrpcn;
	}

	public void setStrdscrpcn(String strdscrpcn) {
		this.strdscrpcn = strdscrpcn;
	}

	@Column(name = "strorgnrsdo", length = 150)
	public String getStrorgnrsdo() {
		return this.strorgnrsdo;
	}

	public void setStrorgnrsdo(String strorgnrsdo) {
		this.strorgnrsdo = strorgnrsdo;
	}

	@Column(name = "strcmntro", length = 150)
	public String getStrcmntro() {
		return this.strcmntro;
	}

	public void setStrcmntro(String strcmntro) {
		this.strcmntro = strcmntro;
	}

	@Column(name = "strdrccn", length = 100)
	public String getStrdrccn() {
		return this.strdrccn;
	}

	public void setStrdrccn(String strdrccn) {
		this.strdrccn = strdrccn;
	}

	@Column(name = "numcntdd", precision = 20)
	public BigDecimal getNumcntdd() {
		return this.numcntdd;
	}

	public void setNumcntdd(BigDecimal numcntdd) {
		this.numcntdd = numcntdd;
	}

	@Column(name = "strprsntcn", length = 300)
	public String getStrprsntcn() {
		return this.strprsntcn;
	}

	public void setStrprsntcn(String strprsntcn) {
		this.strprsntcn = strprsntcn;
	}

	@Column(name = "booldnr")
	public Boolean getBooldnr() {
		return this.booldnr;
	}

	public void setBooldnr(Boolean booldnr) {
		this.booldnr = booldnr;
	}

	@Column(name = "numprco", precision = 20)
	public BigDecimal getNumprco() {
		return this.numprco;
	}

	public void setNumprco(BigDecimal numprco) {
		this.numprco = numprco;
	}

	@Column(name = "intrptcn")
	public Integer getIntrptcn() {
		return intrptcn;
	}

	public void setIntrptcn(Integer intrptcn) {
		this.intrptcn = intrptcn;
	}

	@Column(name = "intpkter")
	public Integer getIntpkter() {
		return this.intpkter;
	}

	public void setIntpkter(Integer intpkter) {
		this.intpkter = intpkter;
	}

	@Column(name = "strmncpo", length = 100)
	public String getStrmncpo() {
		return this.strmncpo;
	}

	public void setStrmncpo(String strmncpo) {
		this.strmncpo = strmncpo;
	}

	@Column(name = "boolactvo")
	public Boolean getBoolactvo() {
		return this.boolactvo;
	}

	public void setBoolactvo(Boolean boolactvo) {
		this.boolactvo = boolactvo;
	}

	@Column(name = "tmastrnmbre", length = 100)
	public String getTmastrnmbre() {
		return this.tmastrnmbre;
	}

	public void setTmastrnmbre(String tmastrnmbre) {
		this.tmastrnmbre = tmastrnmbre;
	}

	@Column(name = "tmestrnmbre", length = 50)
	public String getTmestrnmbre() {
		return this.tmestrnmbre;
	}

	public void setTmestrnmbre(String tmestrnmbre) {
		this.tmestrnmbre = tmestrnmbre;
	}

	@Column(name = "stricno", length = 100)
	public String getStricno() {
		return stricno;
	}

	public void setStricno(String stricno) {
		this.stricno = stricno;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((boolactvo == null) ? 0 : boolactvo.hashCode());
		result = prime * result + ((booldnr == null) ? 0 : booldnr.hashCode());
		result = prime * result + ((intpkres == null) ? 0 : intpkres.hashCode());
		result = prime * result + ((intpkter == null) ? 0 : intpkter.hashCode());
		result = prime * result + ((intrptcn == null) ? 0 : intrptcn.hashCode());
		result = prime * result + ((numcntdd == null) ? 0 : numcntdd.hashCode());
		result = prime * result + ((numprco == null) ? 0 : numprco.hashCode());
		result = prime * result + ((strcmntro == null) ? 0 : strcmntro.hashCode());
		result = prime * result + ((strdrccn == null) ? 0 : strdrccn.hashCode());
		result = prime * result + ((strdscrpcn == null) ? 0 : strdscrpcn.hashCode());
		result = prime * result + ((stricno == null) ? 0 : stricno.hashCode());
		result = prime * result + ((strmncpo == null) ? 0 : strmncpo.hashCode());
		result = prime * result + ((strorgnrsdo == null) ? 0 : strorgnrsdo.hashCode());
		result = prime * result + ((strprsntcn == null) ? 0 : strprsntcn.hashCode());
		result = prime * result + ((tmastrnmbre == null) ? 0 : tmastrnmbre.hashCode());
		result = prime * result + ((tmestrnmbre == null) ? 0 : tmestrnmbre.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ViewTerceroResiduoId other = (ViewTerceroResiduoId) obj;
		if (boolactvo == null) {
			if (other.boolactvo != null)
				return false;
		} else if (!boolactvo.equals(other.boolactvo))
			return false;
		if (booldnr == null) {
			if (other.booldnr != null)
				return false;
		} else if (!booldnr.equals(other.booldnr))
			return false;
		if (intpkres == null) {
			if (other.intpkres != null)
				return false;
		} else if (!intpkres.equals(other.intpkres))
			return false;
		if (intpkter == null) {
			if (other.intpkter != null)
				return false;
		} else if (!intpkter.equals(other.intpkter))
			return false;
		if (intrptcn == null) {
			if (other.intrptcn != null)
				return false;
		} else if (!intrptcn.equals(other.intrptcn))
			return false;
		if (numcntdd == null) {
			if (other.numcntdd != null)
				return false;
		} else if (!numcntdd.equals(other.numcntdd))
			return false;
		if (numprco == null) {
			if (other.numprco != null)
				return false;
		} else if (!numprco.equals(other.numprco))
			return false;
		if (strcmntro == null) {
			if (other.strcmntro != null)
				return false;
		} else if (!strcmntro.equals(other.strcmntro))
			return false;
		if (strdrccn == null) {
			if (other.strdrccn != null)
				return false;
		} else if (!strdrccn.equals(other.strdrccn))
			return false;
		if (strdscrpcn == null) {
			if (other.strdscrpcn != null)
				return false;
		} else if (!strdscrpcn.equals(other.strdscrpcn))
			return false;
		if (stricno == null) {
			if (other.stricno != null)
				return false;
		} else if (!stricno.equals(other.stricno))
			return false;
		if (strmncpo == null) {
			if (other.strmncpo != null)
				return false;
		} else if (!strmncpo.equals(other.strmncpo))
			return false;
		if (strorgnrsdo == null) {
			if (other.strorgnrsdo != null)
				return false;
		} else if (!strorgnrsdo.equals(other.strorgnrsdo))
			return false;
		if (strprsntcn == null) {
			if (other.strprsntcn != null)
				return false;
		} else if (!strprsntcn.equals(other.strprsntcn))
			return false;
		if (tmastrnmbre == null) {
			if (other.tmastrnmbre != null)
				return false;
		} else if (!tmastrnmbre.equals(other.tmastrnmbre))
			return false;
		if (tmestrnmbre == null) {
			if (other.tmestrnmbre != null)
				return false;
		} else if (!tmestrnmbre.equals(other.tmestrnmbre))
			return false;
		return true;
	}

}
