package com.slack.ecotown.model.view;

// Generated 11/12/2017 02:37:30 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewTerceroPerfil generated by hbm2java
 */
@Entity
@Table(name = "view_tercero_perfil", schema = "public")
public class ViewTerceroPerfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private ViewTerceroPerfilId id;

	public ViewTerceroPerfil() {
	}

	public ViewTerceroPerfil(ViewTerceroPerfilId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "intpkter", column = @Column(name = "intpkter")),
			@AttributeOverride(name = "intpkper", column = @Column(name = "intpkper")),
			@AttributeOverride(name = "strnmbre", column = @Column(name = "strnmbre", length = 100)),
			@AttributeOverride(name = "boolestdo", column = @Column(name = "boolestdo")) })
	public ViewTerceroPerfilId getId() {
		return this.id;
	}

	public void setId(ViewTerceroPerfilId id) {
		this.id = id;
	}

}
