package com.slack.ecotown.model.view;

// Generated 11/12/2017 02:37:30 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewTerceroPerfilId generated by hbm2java
 */
@Embeddable
public class ViewTerceroPerfilId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer intpkter;
	private Integer intpkper;
	private String strnmbre;
	private Boolean boolestdo;

	public ViewTerceroPerfilId() {
	}

	public ViewTerceroPerfilId(Integer intpkter, Integer intpkper, String strnmbre, Boolean boolestdo) {
		this.intpkter = intpkter;
		this.intpkper = intpkper;
		this.strnmbre = strnmbre;
		this.boolestdo = boolestdo;
	}

	@Column(name = "intpkter")
	public Integer getIntpkter() {
		return this.intpkter;
	}

	public void setIntpkter(Integer intpkter) {
		this.intpkter = intpkter;
	}

	@Column(name = "intpkper")
	public Integer getIntpkper() {
		return this.intpkper;
	}

	public void setIntpkper(Integer intpkper) {
		this.intpkper = intpkper;
	}

	@Column(name = "strnmbre", length = 100)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@Column(name = "boolestdo")
	public Boolean getBoolestdo() {
		return this.boolestdo;
	}

	public void setBoolestdo(Boolean boolestdo) {
		this.boolestdo = boolestdo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewTerceroPerfilId))
			return false;
		ViewTerceroPerfilId castOther = (ViewTerceroPerfilId) other;

		return ((this.getIntpkter() == castOther.getIntpkter()) || (this.getIntpkter() != null && castOther.getIntpkter() != null && this
				.getIntpkter().equals(castOther.getIntpkter())))
				&& ((this.getIntpkper() == castOther.getIntpkper()) || (this.getIntpkper() != null && castOther.getIntpkper() != null && this
						.getIntpkper().equals(castOther.getIntpkper())))
				&& ((this.getStrnmbre() == castOther.getStrnmbre()) || (this.getStrnmbre() != null && castOther.getStrnmbre() != null && this
						.getStrnmbre().equals(castOther.getStrnmbre())))
				&& ((this.getBoolestdo() == castOther.getBoolestdo()) || (this.getBoolestdo() != null && castOther.getBoolestdo() != null && this
						.getBoolestdo().equals(castOther.getBoolestdo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIntpkter() == null ? 0 : this.getIntpkter().hashCode());
		result = 37 * result + (getIntpkper() == null ? 0 : this.getIntpkper().hashCode());
		result = 37 * result + (getStrnmbre() == null ? 0 : this.getStrnmbre().hashCode());
		result = 37 * result + (getBoolestdo() == null ? 0 : this.getBoolestdo().hashCode());
		return result;
	}

}
