package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Aptitud generated by hbm2java
 */
@Entity
@Table(name = "aptitud", schema = "public")
public class Aptitud implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int intpkapt;
	private Tercero tercero;
	private String strnmbre;

	public Aptitud() {
	}

	public Aptitud(int intpkapt) {
		this.intpkapt = intpkapt;
	}

	public Aptitud(int intpkapt, Tercero tercero, String strnmbre) {
		this.intpkapt = intpkapt;
		this.tercero = tercero;
		this.strnmbre = strnmbre;
	}

	@Id
	@SequenceGenerator(name = "aptitud_intpkapt_seq", sequenceName = "public.aptitud_intpkapt_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "aptitud_intpkapt_seq")
	@Column(name = "intpkapt", unique = true, nullable = false)
	public int getIntpkapt() {
		return this.intpkapt;
	}

	public void setIntpkapt(int intpkapt) {
		this.intpkapt = intpkapt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkter")
	public Tercero getTercero() {
		return this.tercero;
	}

	public void setTercero(Tercero tercero) {
		this.tercero = tercero;
	}

	@Column(name = "strnmbre", length = 100)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

}
