package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Barrio generated by hbm2java
 */
@Entity
@Table(name = "barrio", schema = "public")
public class Barrio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int intpkbar;
	private Comuna comuna;
	private String strnmbre;
	private Integer intcdgpstl;

	public Barrio() {
	}

	public Barrio(int intpkbar) {
		this.intpkbar = intpkbar;
	}

	public Barrio(int intpkbar, Comuna comuna, String strnmbre, Integer intcdgpstl) {
		this.intpkbar = intpkbar;
		this.comuna = comuna;
		this.strnmbre = strnmbre;
		this.intcdgpstl = intcdgpstl;
	}

	@Id
	@SequenceGenerator(name = "barrio_intpkbar_seq", sequenceName = "public.barrio_intpkbar_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "barrio_intpkbar_seq")
	@Column(name = "intpkbar", unique = true, nullable = false)
	public int getIntpkbar() {
		return this.intpkbar;
	}

	public void setIntpkbar(int intpkbar) {
		this.intpkbar = intpkbar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkcom")
	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	@Column(name = "strnmbre", length = 50)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@Column(name = "intcdgpstl")
	public Integer getIntcdgpstl() {
		return this.intcdgpstl;
	}

	public void setIntcdgpstl(Integer intcdgpstl) {
		this.intcdgpstl = intcdgpstl;
	}

}
