package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Calificacion generated by hbm2java
 */
@Entity
@Table(name = "calificacion", schema = "public")
public class Calificacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int intpkcal;
	private Residuo residuo;
	private Integer intrptcn;
	private String strcmntro;

	public Calificacion() {
	}

	public Calificacion(int intpkcal) {
		this.intpkcal = intpkcal;
	}

	public Calificacion(int intpkcal, Residuo residuo, Integer intrptcn, String strcmntro) {
		this.intpkcal = intpkcal;
		this.residuo = residuo;
		this.intrptcn = intrptcn;
		this.strcmntro = strcmntro;
	}

	@Id
	@SequenceGenerator(name = "calificacion_intpkcal_seq", sequenceName = "public.calificacion_intpkcal_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "calificacion_intpkcal_seq")
	@Column(name = "intpkcal", unique = true, nullable = false)
	public int getIntpkcal() {
		return this.intpkcal;
	}

	public void setIntpkcal(int intpkcal) {
		this.intpkcal = intpkcal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkres")
	public Residuo getResiduo() {
		return this.residuo;
	}

	public void setResiduo(Residuo residuo) {
		this.residuo = residuo;
	}

	@Column(name = "intrptcn")
	public Integer getIntrptcn() {
		return this.intrptcn;
	}

	public void setIntrptcn(Integer intrptcn) {
		this.intrptcn = intrptcn;
	}

	@Column(name = "strcmntro", length = 500)
	public String getStrcmntro() {
		return this.strcmntro;
	}

	public void setStrcmntro(String strcmntro) {
		this.strcmntro = strcmntro;
	}

}
