package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Localidad generated by hbm2java
 */
@Entity
@Table(name = "localidad", schema = "public")
public class Localidad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String strpkloc;
	private Region region;
	private BigDecimal biglttd;
	private BigDecimal biglngtd;
	private String strdprtmnto;
	private String strmncpo;
	private String strps;
	private Set<Experiencia> experiencias = new HashSet<Experiencia>(0);
	private Set<Comuna> comunas = new HashSet<Comuna>(0);
	private Set<Residuo> residuos = new HashSet<Residuo>(0);
	private Set<Tercero> terceros = new HashSet<Tercero>(0);

	public Localidad() {
	}

	public Localidad(String strpkloc) {
		this.strpkloc = strpkloc;
	}

	public Localidad(String strpkloc, Region region, BigDecimal biglttd, BigDecimal biglngtd, String strdprtmnto, String strmncpo, String strps,
			Set<Experiencia> experiencias, Set<Comuna> comunas, Set<Residuo> residuos, Set<Tercero> terceros) {
		this.strpkloc = strpkloc;
		this.region = region;
		this.biglttd = biglttd;
		this.biglngtd = biglngtd;
		this.strdprtmnto = strdprtmnto;
		this.strmncpo = strmncpo;
		this.strps = strps;
		this.experiencias = experiencias;
		this.comunas = comunas;
		this.residuos = residuos;
		this.terceros = terceros;
	}

	@Id
	@Column(name = "strpkloc", unique = true, nullable = false, length = 100)
	public String getStrpkloc() {
		return this.strpkloc;
	}

	public void setStrpkloc(String strpkloc) {
		this.strpkloc = strpkloc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intrgn")
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "biglttd", precision = 20, scale = 14)
	public BigDecimal getBiglttd() {
		return this.biglttd;
	}

	public void setBiglttd(BigDecimal biglttd) {
		this.biglttd = biglttd;
	}

	@Column(name = "biglngtd", precision = 20, scale = 14)
	public BigDecimal getBiglngtd() {
		return this.biglngtd;
	}

	public void setBiglngtd(BigDecimal biglngtd) {
		this.biglngtd = biglngtd;
	}

	@Column(name = "strdprtmnto", length = 100)
	public String getStrdprtmnto() {
		return this.strdprtmnto;
	}

	public void setStrdprtmnto(String strdprtmnto) {
		this.strdprtmnto = strdprtmnto;
	}

	@Column(name = "strmncpo", length = 100)
	public String getStrmncpo() {
		return this.strmncpo;
	}

	public void setStrmncpo(String strmncpo) {
		this.strmncpo = strmncpo;
	}

	@Column(name = "strps", length = 100)
	public String getStrps() {
		return this.strps;
	}

	public void setStrps(String strps) {
		this.strps = strps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localidad")
	public Set<Experiencia> getExperiencias() {
		return this.experiencias;
	}

	public void setExperiencias(Set<Experiencia> experiencias) {
		this.experiencias = experiencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localidad")
	public Set<Comuna> getComunas() {
		return this.comunas;
	}

	public void setComunas(Set<Comuna> comunas) {
		this.comunas = comunas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localidad")
	public Set<Residuo> getResiduos() {
		return this.residuos;
	}

	public void setResiduos(Set<Residuo> residuos) {
		this.residuos = residuos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localidad")
	public Set<Tercero> getTerceros() {
		return this.terceros;
	}

	public void setTerceros(Set<Tercero> terceros) {
		this.terceros = terceros;
	}

}
