package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Membresia generated by hbm2java
 */
@Entity
@Table(name = "membresia", schema = "public")
public class Membresia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpkmem;
	private String strnombre;
	private BigDecimal numprco;
	private Boolean boolpplr;
	private String strimgn;
	private Set<Tercero> terceros = new HashSet<Tercero>();

	public Membresia() {
	}

	public Membresia(int intpkmem) {
		this.intpkmem = intpkmem;
	}

	public Membresia(int intpkmem, String strnombre, BigDecimal numprco, Boolean boolpplr, String strimgn, Set<Tercero> terceros) {
		this.intpkmem = intpkmem;
		this.strnombre = strnombre;
		this.numprco = numprco;
		this.boolpplr = boolpplr;
		this.strimgn = strimgn;
		this.terceros = terceros;
	}

	@Id
	@SequenceGenerator(name = "membresia_intpkmem_seq", sequenceName = "public.membresia_intpkmem_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "membresia_intpkmem_seq")
	@Column(name = "intpkmem", unique = true, nullable = false)
	public int getIntpkmem() {
		return this.intpkmem;
	}

	public void setIntpkmem(int intpkmem) {
		this.intpkmem = intpkmem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "membresia")
	public Set<Tercero> getTerceros() {
		return terceros;
	}

	public void setTerceros(Set<Tercero> terceros) {
		this.terceros = terceros;
	}

	@Column(name = "strimgn", length = 50)
	public String getStrimgn() {
		return strimgn;
	}

	public void setStrimgn(String strimgn) {
		this.strimgn = strimgn;
	}

	@Column(name = "strnombre", length = 100)
	public String getStrnombre() {
		return this.strnombre;
	}

	public void setStrnombre(String strnombre) {
		this.strnombre = strnombre;
	}

	@Column(name = "numprco", precision = 20)
	public BigDecimal getNumprco() {
		return this.numprco;
	}

	public void setNumprco(BigDecimal numprco) {
		this.numprco = numprco;
	}

	@Column(name = "boolpplr")
	public Boolean getBoolpplr() {
		return this.boolpplr;
	}

	public void setBoolpplr(Boolean boolpplr) {
		this.boolpplr = boolpplr;
	}

}
