package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "modulo", schema = "public")
public class Modulo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpkmod;
	private String strnombre;
	private String stractn;
	private String stricno;
	private Boolean boolestdo;
	private String strdscrpcn;
	private Set<Recurso> recursos = new HashSet<Recurso>(0);
	private Set<PerfilModulo> perfilModulos = new HashSet<PerfilModulo>(0);

	public Modulo() {
	}

	public Modulo(int intpkmod) {
		this.intpkmod = intpkmod;
	}

	public Modulo(int intpkmod, String strnombre, Boolean boolestdo, String strdscrpcn, Set<Recurso> recursos, Set<PerfilModulo> perfilModulos) {
		this.intpkmod = intpkmod;
		this.strnombre = strnombre;
		this.boolestdo = boolestdo;
		this.strdscrpcn = strdscrpcn;
		this.recursos = recursos;
		this.perfilModulos = perfilModulos;
	}

	@Id
	@SequenceGenerator(name = "modulo_intpkmod_seq", sequenceName = "public.modulo_intpkmod_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "modulo_intpkmod_seq")
	@Column(name = "intpkmod", unique = true, nullable = false)
	public int getIntpkmod() {
		return this.intpkmod;
	}

	public void setIntpkmod(int intpkmod) {
		this.intpkmod = intpkmod;
	}

	@Column(name = "strnombre", length = 50)
	public String getStrnombre() {
		return this.strnombre;
	}

	public void setStrnombre(String strnombre) {
		this.strnombre = strnombre;
	}

	@Column(name = "stractn", length = 50)
	public String getStractn() {
		return stractn;
	}

	public void setStractn(String stractn) {
		this.stractn = stractn;
	}

	@Column(name = "stricno", length = 50)
	public String getStricno() {
		return stricno;
	}

	public void setStricno(String stricno) {
		this.stricno = stricno;
	}

	@Column(name = "boolestdo")
	public Boolean getBoolestdo() {
		return this.boolestdo;
	}

	public void setBoolestdo(Boolean boolestdo) {
		this.boolestdo = boolestdo;
	}

	@Column(name = "strdscrpcn", length = 200)
	public String getStrdscrpcn() {
		return this.strdscrpcn;
	}

	public void setStrdscrpcn(String strdscrpcn) {
		this.strdscrpcn = strdscrpcn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modulo")
	public Set<Recurso> getRecursos() {
		return this.recursos;
	}

	public void setRecursos(Set<Recurso> recursos) {
		this.recursos = recursos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modulo")
	public Set<PerfilModulo> getPerfilModulos() {
		return this.perfilModulos;
	}

	public void setPerfilModulos(Set<PerfilModulo> perfilModulos) {
		this.perfilModulos = perfilModulos;
	}

}
