package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Parametrica generated by hbm2java
 */
@Entity
@Table(name = "parametrica", schema = "public")
public class Parametrica implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpkpar;
	private String strnmbre;
	private String strvlr;
	private String strdscrpcn;

	public Parametrica() {
	}

	public Parametrica(int intpkpar) {
		this.intpkpar = intpkpar;
	}

	public Parametrica(int intpkpar, String strnmbre, String strvlr, String strdscrpcn) {
		this.intpkpar = intpkpar;
		this.strnmbre = strnmbre;
		this.strvlr = strvlr;
		this.strdscrpcn = strdscrpcn;
	}

	@Id
	@SequenceGenerator(name = "parametrica_intpkpar_seq", sequenceName = "public.parametrica_intpkpar_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "parametrica_intpkpar_seq")
	@Column(name = "intpkpar", unique = true, nullable = false)
	public int getIntpkpar() {
		return this.intpkpar;
	}

	public void setIntpkpar(int intpkpar) {
		this.intpkpar = intpkpar;
	}

	@Column(name = "strnmbre", length = 100)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@Column(name = "strvlr", length = 3000)
	public String getStrvlr() {
		return this.strvlr;
	}

	public void setStrvlr(String strvlr) {
		this.strvlr = strvlr;
	}

	@Column(name = "strdscrpcn", length = 100)
	public String getStrdscrpcn() {
		return this.strdscrpcn;
	}

	public void setStrdscrpcn(String strdscrpcn) {
		this.strdscrpcn = strdscrpcn;
	}

}
