package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PerfilPermiso generated by hbm2java
 */
@Entity
@Table(name = "perfil_permiso", schema = "public")
public class PerfilPermiso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpkperperm;
	private Perfil perfil;
	private Permiso permiso;

	public PerfilPermiso() {
	}

	public PerfilPermiso(int intpkperperm) {
		this.intpkperperm = intpkperperm;
	}

	public PerfilPermiso(int intpkperperm, Perfil perfil, Permiso permiso) {
		this.intpkperperm = intpkperperm;
		this.perfil = perfil;
		this.permiso = permiso;
	}

	@Id
	@SequenceGenerator(name = "perfil_permiso_intpkperperm_seq", sequenceName = "public.perfil_permiso_intpkperperm_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "perfil_permiso_intpkperperm_seq")
	@Column(name = "intpkperperm", unique = true, nullable = false)
	public int getIntpkperperm() {
		return this.intpkperperm;
	}

	public void setIntpkperperm(int intpkperperm) {
		this.intpkperperm = intpkperperm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkper")
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkperm")
	public Permiso getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Permiso permiso) {
		this.permiso = permiso;
	}

}
