package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", schema = "public")
public class Perfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpkper;
	private String strnmbre;
	private Boolean boolestdo;
	private Set<PerfilPermiso> perfilPermisos = new HashSet<PerfilPermiso>(0);
	private Set<PerfilModulo> perfilModulos = new HashSet<PerfilModulo>(0);
	private Set<Tercero> terceros = new HashSet<Tercero>(0);

	public Perfil() {
	}

	public Perfil(int intpkper) {
		this.intpkper = intpkper;
	}

	public Perfil(int intpkper, String strnmbre, Boolean boolestdo, Set<PerfilPermiso> perfilPermisos, Set<PerfilModulo> perfilModulos,
			Set<Tercero> terceros) {
		this.intpkper = intpkper;
		this.strnmbre = strnmbre;
		this.boolestdo = boolestdo;
		this.perfilPermisos = perfilPermisos;
		this.perfilModulos = perfilModulos;
		this.terceros = terceros;
	}

	@Id
	@SequenceGenerator(name = "perfil_intpkper_seq", sequenceName = "public.perfil_intpkper_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "perfil_intpkper_seq")
	@Column(name = "intpkper", unique = true, nullable = false)
	public int getIntpkper() {
		return this.intpkper;
	}

	public void setIntpkper(int intpkper) {
		this.intpkper = intpkper;
	}

	@Column(name = "strnmbre", length = 100)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@Column(name = "boolestdo")
	public Boolean getBoolestdo() {
		return this.boolestdo;
	}

	public void setBoolestdo(Boolean boolestdo) {
		this.boolestdo = boolestdo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<PerfilPermiso> getPerfilPermisos() {
		return this.perfilPermisos;
	}

	public void setPerfilPermisos(Set<PerfilPermiso> perfilPermisos) {
		this.perfilPermisos = perfilPermisos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<PerfilModulo> getPerfilModulos() {
		return this.perfilModulos;
	}

	public void setPerfilModulos(Set<PerfilModulo> perfilModulos) {
		this.perfilModulos = perfilModulos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Tercero> getTerceros() {
		return this.terceros;
	}

	public void setTerceros(Set<Tercero> terceros) {
		this.terceros = terceros;
	}

}
