package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name = "permiso", schema = "public")
public class Permiso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpkperm;
	private String strnmbre;
	private Boolean boolestdo;
	private String stricno;
	private Set<PerfilPermiso> perfilPermisos = new HashSet<PerfilPermiso>(0);

	public Permiso() {
	}

	public Permiso(int intpkperm) {
		this.intpkperm = intpkperm;
	}

	public Permiso(int intpkperm, String strnmbre, Boolean boolestdo, String stricno, Set<PerfilPermiso> perfilPermisos) {
		this.intpkperm = intpkperm;
		this.strnmbre = strnmbre;
		this.boolestdo = boolestdo;
		this.stricno = stricno;
		this.perfilPermisos = perfilPermisos;
	}

	@Id
	@Column(name = "intpkperm", unique = true, nullable = false)
	public int getIntpkperm() {
		return this.intpkperm;
	}

	public void setIntpkperm(int intpkperm) {
		this.intpkperm = intpkperm;
	}

	@Column(name = "strnmbre", length = 50)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@Column(name = "boolestdo")
	public Boolean getBoolestdo() {
		return this.boolestdo;
	}

	public void setBoolestdo(Boolean boolestdo) {
		this.boolestdo = boolestdo;
	}

	@Column(name = "stricno", length = 50)
	public String getStricno() {
		return this.stricno;
	}

	public void setStricno(String stricno) {
		this.stricno = stricno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permiso")
	public Set<PerfilPermiso> getPerfilPermisos() {
		return this.perfilPermisos;
	}

	public void setPerfilPermisos(Set<PerfilPermiso> perfilPermisos) {
		this.perfilPermisos = perfilPermisos;
	}

}
