package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TipoIdentificacion generated by hbm2java
 */
@Entity
@Table(name = "tipo_identificacion", schema = "public")
public class TipoIdentificacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpktipide;
	private String strnmbre;
	private Set<Tercero> terceros = new HashSet<Tercero>(0);

	public TipoIdentificacion() {
	}

	public TipoIdentificacion(int intpktipide) {
		this.intpktipide = intpktipide;
	}

	public TipoIdentificacion(int intpktipide, String strnmbre, Set<Tercero> terceros) {
		this.intpktipide = intpktipide;
		this.strnmbre = strnmbre;
		this.terceros = terceros;
	}

	@Id
	@SequenceGenerator(name = "tipo_identificacion_intpktipide_seq", sequenceName = "public.tipo_identificacion_intpktipide_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tipo_identificacion_intpktipide_seq")
	@Column(name = "intpktipide", unique = true, nullable = false)
	public int getIntpktipide() {
		return this.intpktipide;
	}

	public void setIntpktipide(int intpktipide) {
		this.intpktipide = intpktipide;
	}

	@Column(name = "strnmbre", length = 100)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoIdentificacion")
	public Set<Tercero> getTerceros() {
		return this.terceros;
	}

	public void setTerceros(Set<Tercero> terceros) {
		this.terceros = terceros;
	}

}
