package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TipoPago generated by hbm2java
 */
@Entity
@Table(name = "tipo_pago", schema = "public")
public class TipoPago implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpktippag;
	private String strnmbre;
	private Set<Anuncio> anuncios = new HashSet<Anuncio>(0);

	public TipoPago() {
	}

	public TipoPago(int intpktippag) {
		this.intpktippag = intpktippag;
	}

	public TipoPago(int intpktippag, String strnmbre, Set<Anuncio> anuncios) {
		this.intpktippag = intpktippag;
		this.strnmbre = strnmbre;
		this.anuncios = anuncios;
	}

	@Id
	@SequenceGenerator(name = "tipo_pago_intpktippag_seq", sequenceName = "public.tipo_pago_intpktippag_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tipo_pago_intpktippag_seq")
	@Column(name = "intpktippag", unique = true, nullable = false)
	public int getIntpktippag() {
		return this.intpktippag;
	}

	public void setIntpktippag(int intpktippag) {
		this.intpktippag = intpktippag;
	}

	@Column(name = "strnmbre", length = 50)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPago")
	public Set<Anuncio> getAnuncios() {
		return this.anuncios;
	}

	public void setAnuncios(Set<Anuncio> anuncios) {
		this.anuncios = anuncios;
	}

}
