package com.slack.ecotown.model;

// Generated 23/01/2018 03:56:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMaterialGrupo generated by hbm2java
 */
@Entity
@Table(name = "tipo_material_grupo", schema = "public")
public class TipoMaterialGrupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpktipmatgru;
	private String strnmbre;
	private Set<TipoMaterial> tipoMaterials = new HashSet<TipoMaterial>(0);

	public TipoMaterialGrupo() {
	}

	public TipoMaterialGrupo(int intpktipmatgru) {
		this.intpktipmatgru = intpktipmatgru;
	}

	public TipoMaterialGrupo(int intpktipmatgru, String strnmbre, Set<TipoMaterial> tipoMaterials) {
		this.intpktipmatgru = intpktipmatgru;
		this.strnmbre = strnmbre;
		this.tipoMaterials = tipoMaterials;
	}

	@Id
	@Column(name = "intpktipmatgru", unique = true, nullable = false)
	public int getIntpktipmatgru() {
		return this.intpktipmatgru;
	}

	public void setIntpktipmatgru(int intpktipmatgru) {
		this.intpktipmatgru = intpktipmatgru;
	}

	@Column(name = "strnmbre", length = 100)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMaterialGrupo")
	public Set<TipoMaterial> getTipoMaterials() {
		return tipoMaterials;
	}

	public void setTipoMaterials(Set<TipoMaterial> tipoMaterials) {
		this.tipoMaterials = tipoMaterials;
	}

}
