package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Titulo generated by hbm2java
 */
@Entity
@Table(name = "titulo", schema = "public")
public class Titulo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpktit;
	private String strnmbre;
	private Set<Educacion> educacions = new HashSet<Educacion>(0);

	public Titulo() {
	}

	public Titulo(int intpktit) {
		this.intpktit = intpktit;
	}

	public Titulo(int intpktit, String strnmbre, Set<Educacion> educacions) {
		this.intpktit = intpktit;
		this.strnmbre = strnmbre;
		this.educacions = educacions;
	}

	@Id
	@SequenceGenerator(name = "titulo_intpktit_seq", sequenceName = "public.titulo_intpktit_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "titulo_intpktit_seq")
	@Column(name = "intpktit", unique = true, nullable = false)
	public int getIntpktit() {
		return this.intpktit;
	}

	public void setIntpktit(int intpktit) {
		this.intpktit = intpktit;
	}

	@Column(name = "strnmbre", length = 100)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titulo")
	public Set<Educacion> getEducacions() {
		return this.educacions;
	}

	public void setEducacions(Set<Educacion> educacions) {
		this.educacions = educacions;
	}

}
