package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Vigencia generated by hbm2java
 */
@Entity
@Table(name = "vigencia", schema = "public")
public class Vigencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpkvig;
	private Integer intintrvlo;
	private Set<Anuncio> anuncios = new HashSet<Anuncio>(0);

	public Vigencia() {
	}

	public Vigencia(int intpkvig) {
		this.intpkvig = intpkvig;
	}

	public Vigencia(int intpkvig, Integer intintrvlo, Set<Anuncio> anuncios) {
		this.intpkvig = intpkvig;
		this.intintrvlo = intintrvlo;
		this.anuncios = anuncios;
	}

	@Id
	@SequenceGenerator(name = "vigencia_intpkvig_seq", sequenceName = "public.vigencia_intpkvig_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "vigencia_intpkvig_seq")
	@Column(name = "intpkvig", unique = true, nullable = false)
	public int getIntpkvig() {
		return this.intpkvig;
	}

	public void setIntpkvig(int intpkvig) {
		this.intpkvig = intpkvig;
	}

	@Column(name = "intintrvlo")
	public Integer getIntintrvlo() {
		return this.intintrvlo;
	}

	public void setIntintrvlo(Integer intintrvlo) {
		this.intintrvlo = intintrvlo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vigencia")
	public Set<Anuncio> getAnuncios() {
		return this.anuncios;
	}

	public void setAnuncios(Set<Anuncio> anuncios) {
		this.anuncios = anuncios;
	}

}
