package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Anuncio generated by hbm2java
 */
@Entity
@Table(name = "anuncio", schema = "public")
public class Anuncio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int intpkanu;
	private Tercero tercero;
	private Vigencia vigencia;
	private TipoPago tipoPago;
	private String strdscrpcn;
	private BigDecimal numcsto;

	public Anuncio() {
	}

	public Anuncio(int intpkanu) {
		this.intpkanu = intpkanu;
	}

	public Anuncio(int intpkanu, Tercero tercero, Vigencia vigencia, TipoPago tipoPago, String strdscrpcn, BigDecimal numcsto) {
		this.intpkanu = intpkanu;
		this.tercero = tercero;
		this.vigencia = vigencia;
		this.tipoPago = tipoPago;
		this.strdscrpcn = strdscrpcn;
		this.numcsto = numcsto;
	}

	@Id
	@SequenceGenerator(name = "anuncio_intpkanu_seq", sequenceName = "public.anuncio_intpkanu_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "anuncio_intpkanu_seq")
	@Column(name = "intpkanu", unique = true, nullable = false)
	public int getIntpkanu() {
		return this.intpkanu;
	}

	public void setIntpkanu(int intpkanu) {
		this.intpkanu = intpkanu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkter")
	public Tercero getTercero() {
		return this.tercero;
	}

	public void setTercero(Tercero tercero) {
		this.tercero = tercero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkvig")
	public Vigencia getVigencia() {
		return this.vigencia;
	}

	public void setVigencia(Vigencia vigencia) {
		this.vigencia = vigencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpktippag")
	public TipoPago getTipoPago() {
		return this.tipoPago;
	}

	public void setTipoPago(TipoPago tipoPago) {
		this.tipoPago = tipoPago;
	}

	@Column(name = "strdscrpcn", length = 100)
	public String getStrdscrpcn() {
		return this.strdscrpcn;
	}

	public void setStrdscrpcn(String strdscrpcn) {
		this.strdscrpcn = strdscrpcn;
	}

	@Column(name = "numcsto", precision = 20)
	public BigDecimal getNumcsto() {
		return this.numcsto;
	}

	public void setNumcsto(BigDecimal numcsto) {
		this.numcsto = numcsto;
	}

}
