package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Buzon generated by hbm2java
 */
@Entity
@Table(name = "buzon", schema = "public")
public class Buzon implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int intpkbuz;
	private Tercero terceroByIntpkterpro;
	private Tercero terceroByIntpkteremp;
	private String strasnto;
	private String strdscrpcn;
	private Boolean boolldo;
	private Boolean boolactvo;

	public Buzon() {
	}

	public Buzon(int intpkbuz) {
		this.intpkbuz = intpkbuz;
	}

	public Buzon(int intpkbuz, Tercero terceroByIntpkterpro, Tercero terceroByIntpkteremp, String strasnto, String strdscrpcn, Boolean boolldo,
			Boolean boolactvo) {
		this.intpkbuz = intpkbuz;
		this.terceroByIntpkterpro = terceroByIntpkterpro;
		this.terceroByIntpkteremp = terceroByIntpkteremp;
		this.strasnto = strasnto;
		this.strdscrpcn = strdscrpcn;
		this.boolldo = boolldo;
		this.boolactvo = boolactvo;
	}

	@Id
	@SequenceGenerator(name = "buzon_intpkbuz_seq", sequenceName = "public.buzon_intpkbuz_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "buzon_intpkbuz_seq")
	@Column(name = "intpkbuz", unique = true, nullable = false)
	public int getIntpkbuz() {
		return this.intpkbuz;
	}

	public void setIntpkbuz(int intpkbuz) {
		this.intpkbuz = intpkbuz;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkterpro")
	public Tercero getTerceroByIntpkterpro() {
		return this.terceroByIntpkterpro;
	}

	public void setTerceroByIntpkterpro(Tercero terceroByIntpkterpro) {
		this.terceroByIntpkterpro = terceroByIntpkterpro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkteremp")
	public Tercero getTerceroByIntpkteremp() {
		return this.terceroByIntpkteremp;
	}

	public void setTerceroByIntpkteremp(Tercero terceroByIntpkteremp) {
		this.terceroByIntpkteremp = terceroByIntpkteremp;
	}

	@Column(name = "strasnto", length = 100)
	public String getStrasnto() {
		return this.strasnto;
	}

	public void setStrasnto(String strasnto) {
		this.strasnto = strasnto;
	}

	@Column(name = "strdscrpcn", length = 3000)
	public String getStrdscrpcn() {
		return this.strdscrpcn;
	}

	public void setStrdscrpcn(String strdscrpcn) {
		this.strdscrpcn = strdscrpcn;
	}

	@Column(name = "boolldo")
	public Boolean getBoolldo() {
		return this.boolldo;
	}

	public void setBoolldo(Boolean boolldo) {
		this.boolldo = boolldo;
	}

	@Column(name = "boolactvo")
	public Boolean getBoolactvo() {
		return this.boolactvo;
	}

	public void setBoolactvo(Boolean boolactvo) {
		this.boolactvo = boolactvo;
	}

}
