package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Comuna generated by hbm2java
 */
@Entity
@Table(name = "comuna", schema = "public")
public class Comuna implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpkcom;
	private Localidad localidad;
	private String strnmbre;
	private Set<Barrio> barrios = new HashSet<Barrio>(0);

	public Comuna() {
	}

	public Comuna(int intpkcom) {
		this.intpkcom = intpkcom;
	}

	public Comuna(int intpkcom, Localidad localidad, String strnmbre, Set<Barrio> barrios) {
		this.intpkcom = intpkcom;
		this.localidad = localidad;
		this.strnmbre = strnmbre;
		this.barrios = barrios;
	}

	@Id
	@SequenceGenerator(name = "comuna_intpkcom_seq", sequenceName = "public.comuna_intpkcom_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "comuna_intpkcom_seq")
	@Column(name = "intpkcom", unique = true, nullable = false)
	public int getIntpkcom() {
		return this.intpkcom;
	}

	public void setIntpkcom(int intpkcom) {
		this.intpkcom = intpkcom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "strpkloc")
	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	@Column(name = "strnmbre", length = 50)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comuna")
	public Set<Barrio> getBarrios() {
		return this.barrios;
	}

	public void setBarrios(Set<Barrio> barrios) {
		this.barrios = barrios;
	}

}
