package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Educacion generated by hbm2java
 */
@Entity
@Table(name = "educacion", schema = "public")
public class Educacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int intpkedu;
	private Tercero tercero;
	private Titulo titulo;
	private String strunvrsdd;
	private String strnta;
	private Date dateinco;
	private Date datefn;
	private String strdscrpcn;

	public Educacion() {
	}

	public Educacion(int intpkedu) {
		this.intpkedu = intpkedu;
	}

	public Educacion(int intpkedu, Tercero tercero, Titulo titulo, String strunvrsdd, String strnta, Date dateinco, Date datefn, String strdscrpcn) {
		this.intpkedu = intpkedu;
		this.tercero = tercero;
		this.titulo = titulo;
		this.strunvrsdd = strunvrsdd;
		this.strnta = strnta;
		this.dateinco = dateinco;
		this.datefn = datefn;
		this.strdscrpcn = strdscrpcn;
	}

	@Id
	@SequenceGenerator(name = "educacion_intpkedu_seq", sequenceName = "public.educacion_intpkedu_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "educacion_intpkedu_seq")
	@Column(name = "intpkedu", unique = true, nullable = false)
	public int getIntpkedu() {
		return this.intpkedu;
	}

	public void setIntpkedu(int intpkedu) {
		this.intpkedu = intpkedu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkter")
	public Tercero getTercero() {
		return this.tercero;
	}

	public void setTercero(Tercero tercero) {
		this.tercero = tercero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpktit")
	public Titulo getTitulo() {
		return this.titulo;
	}

	public void setTitulo(Titulo titulo) {
		this.titulo = titulo;
	}

	@Column(name = "strunvrsdd", length = 100)
	public String getStrunvrsdd() {
		return this.strunvrsdd;
	}

	public void setStrunvrsdd(String strunvrsdd) {
		this.strunvrsdd = strunvrsdd;
	}

	@Column(name = "strnta", length = 200)
	public String getStrnta() {
		return this.strnta;
	}

	public void setStrnta(String strnta) {
		this.strnta = strnta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateinco", length = 13)
	public Date getDateinco() {
		return this.dateinco;
	}

	public void setDateinco(Date dateinco) {
		this.dateinco = dateinco;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datefn", length = 13)
	public Date getDatefn() {
		return this.datefn;
	}

	public void setDatefn(Date datefn) {
		this.datefn = datefn;
	}

	@Column(name = "strdscrpcn", length = 200)
	public String getStrdscrpcn() {
		return this.strdscrpcn;
	}

	public void setStrdscrpcn(String strdscrpcn) {
		this.strdscrpcn = strdscrpcn;
	}

}
