package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Favorito generated by hbm2java
 */
@Entity
@Table(name = "favorito", schema = "public")
public class Favorito implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int intpkfav;
	private Tercero tercero;
	private TipoMaterial tipoMaterial;

	public Favorito() {
	}

	public Favorito(int intpkfav) {
		this.intpkfav = intpkfav;
	}

	public Favorito(int intpkfav, Tercero tercero, TipoMaterial tipoMaterial) {
		this.intpkfav = intpkfav;
		this.tercero = tercero;
		this.tipoMaterial = tipoMaterial;
	}

	@Id
	@SequenceGenerator(name = "favorito_intpkfav_seq", sequenceName = "public.favorito_intpkfav_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "favorito_intpkfav_seq")
	@Column(name = "intpkfav", unique = true, nullable = false)
	public int getIntpkfav() {
		return this.intpkfav;
	}

	public void setIntpkfav(int intpkfav) {
		this.intpkfav = intpkfav;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkter")
	public Tercero getTercero() {
		return this.tercero;
	}

	public void setTercero(Tercero tercero) {
		this.tercero = tercero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpktipmat")
	public TipoMaterial getTipoMaterial() {
		return this.tipoMaterial;
	}

	public void setTipoMaterial(TipoMaterial tipoMaterial) {
		this.tipoMaterial = tipoMaterial;
	}

}
