package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * FotoResiduo generated by hbm2java
 */
@Entity
@Table(name = "foto_residuo", schema = "public")
public class FotoResiduo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int intpkfotres;
	private Residuo residuo;
	private byte[] bytedcmnto;

	public FotoResiduo() {
	}

	public FotoResiduo(int intpkfotres) {
		this.intpkfotres = intpkfotres;
	}

	public FotoResiduo(int intpkfotres, Residuo residuo, byte[] bytedcmnto) {
		this.intpkfotres = intpkfotres;
		this.residuo = residuo;
		this.bytedcmnto = bytedcmnto;
	}

	@Id
	@SequenceGenerator(name = "foto_residuo_intpkfotres_seq", sequenceName = "public.foto_residuo_intpkfotres_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "foto_residuo_intpkfotres_seq")
	@Column(name = "intpkfotres", unique = true, nullable = false)
	public int getIntpkfotres() {
		return this.intpkfotres;
	}

	public void setIntpkfotres(int intpkfotres) {
		this.intpkfotres = intpkfotres;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkres")
	public Residuo getResiduo() {
		return this.residuo;
	}

	public void setResiduo(Residuo residuo) {
		this.residuo = residuo;
	}

	@Column(name = "bytedcmnto")
	public byte[] getBytedcmnto() {
		return this.bytedcmnto;
	}

	public void setBytedcmnto(byte[] bytedcmnto) {
		this.bytedcmnto = bytedcmnto;
	}

}
