package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PerfilModulo generated by hbm2java
 */
@Entity
@Table(name = "perfil_modulo", schema = "public")
public class PerfilModulo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpkpermod;
	private Modulo modulo;
	private Perfil perfil;

	public PerfilModulo() {
	}

	public PerfilModulo(int intpkpermod) {
		this.intpkpermod = intpkpermod;
	}

	public PerfilModulo(int intpkpermod, Modulo modulo, Perfil perfil) {
		this.intpkpermod = intpkpermod;
		this.modulo = modulo;
		this.perfil = perfil;
	}

	@Id
	@SequenceGenerator(name = "perfil_modulo_intpkpermod_seq", sequenceName = "public.perfil_modulo_intpkpermod_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "perfil_modulo_intpkpermod_seq")
	@Column(name = "intpkpermod", unique = true, nullable = false)
	public int getIntpkpermod() {
		return this.intpkpermod;
	}

	public void setIntpkpermod(int intpkpermod) {
		this.intpkpermod = intpkpermod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkmod")
	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkper")
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

}
