package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", schema = "public")
public class Region implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpkreg;
	private String strnmbre;
	private Set<Localidad> localidads = new HashSet<Localidad>(0);

	public Region() {
	}

	public Region(int intpkreg) {
		this.intpkreg = intpkreg;
	}

	public Region(int intpkreg, String strnmbre, Set<Localidad> localidads) {
		this.intpkreg = intpkreg;
		this.strnmbre = strnmbre;
		this.localidads = localidads;
	}

	@Id
	@SequenceGenerator(name = "region_intpkreg_seq", sequenceName = "public.region_intpkreg_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "region_intpkreg_seq")
	@Column(name = "intpkreg", unique = true, nullable = false)
	public int getIntpkreg() {
		return this.intpkreg;
	}

	public void setIntpkreg(int intpkreg) {
		this.intpkreg = intpkreg;
	}

	@Column(name = "strnmbre", length = 50)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Localidad> getLocalidads() {
		return this.localidads;
	}

	public void setLocalidads(Set<Localidad> localidads) {
		this.localidads = localidads;
	}

}
