package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Residuo generated by hbm2java
 */
@Entity
@Table(name = "residuo", schema = "public")
public class Residuo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpkres;
	private Tercero tercero;
	private Localidad localidad;
	private TipoMaterial tipoMaterial;
	private TipoMedida tipoMedida;
	private String strdscrpcn;
	private String strorgnrsdo;
	private String strcmntro;
	private String strdrccn;
	private BigDecimal numcntdd;
	private String strprsntcn;
	private String strrta;
	private String strnmbre;
	private Boolean booldnr;
	private BigDecimal numprco;
	private Boolean boolactvo;
	private Date datefchpblccn;
	private Set<Calificacion> calificacions = new HashSet<Calificacion>(0);
	private Set<FotoResiduo> fotoResiduos = new HashSet<FotoResiduo>(0);

	public Residuo() {
	}

	public Residuo(int intpkres) {
		this.intpkres = intpkres;
	}

	public Residuo(int intpkres, Tercero tercero, Localidad localidad, TipoMaterial tipoMaterial, TipoMedida tipoMedida, String strdscrpcn,
			String strorgnrsdo, String strcmntro, String strdrccn, BigDecimal numcntdd, String strprsntcn, String strrta, String strnmbre,
			Boolean booldnr, BigDecimal numprco, Boolean boolactvo, Date datefchpblccn, Set<Calificacion> calificacions, Set<FotoResiduo> fotoResiduos) {
		this.intpkres = intpkres;
		this.tercero = tercero;
		this.localidad = localidad;
		this.tipoMaterial = tipoMaterial;
		this.tipoMedida = tipoMedida;
		this.strdscrpcn = strdscrpcn;
		this.strorgnrsdo = strorgnrsdo;
		this.strcmntro = strcmntro;
		this.strdrccn = strdrccn;
		this.numcntdd = numcntdd;
		this.strprsntcn = strprsntcn;
		this.strrta = strrta;
		this.strnmbre = strnmbre;
		this.booldnr = booldnr;
		this.numprco = numprco;
		this.boolactvo = boolactvo;
		this.datefchpblccn = datefchpblccn;
		this.calificacions = calificacions;
		this.fotoResiduos = fotoResiduos;
	}

	@Id
	@SequenceGenerator(name = "residuo_intpkres_seq", sequenceName = "public.residuo_intpkres_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "residuo_intpkres_seq")
	@Column(name = "intpkres", unique = true, nullable = false)
	public int getIntpkres() {
		return this.intpkres;
	}

	public void setIntpkres(int intpkres) {
		this.intpkres = intpkres;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkter")
	public Tercero getTercero() {
		return this.tercero;
	}

	public void setTercero(Tercero tercero) {
		this.tercero = tercero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "strpkloc")
	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intpktipmed")
	public TipoMedida getTipoMedida() {
		return tipoMedida;
	}

	public void setTipoMedida(TipoMedida tipoMedida) {
		this.tipoMedida = tipoMedida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpktipmat")
	public TipoMaterial getTipoMaterial() {
		return this.tipoMaterial;
	}

	public void setTipoMaterial(TipoMaterial tipoMaterial) {
		this.tipoMaterial = tipoMaterial;
	}

	@Column(name = "strdscrpcn", length = 150)
	public String getStrdscrpcn() {
		return this.strdscrpcn;
	}

	public void setStrdscrpcn(String strdscrpcn) {
		this.strdscrpcn = strdscrpcn;
	}

	@Column(name = "strnmbre", length = 150)
	public String getStrnmbre() {
		return strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@Column(name = "strrta", length = 150)
	public String getStrrta() {
		return strrta;
	}

	public void setStrrta(String strrta) {
		this.strrta = strrta;
	}

	@Column(name = "strorgnrsdo", length = 150)
	public String getStrorgnrsdo() {
		return this.strorgnrsdo;
	}

	public void setStrorgnrsdo(String strorgnrsdo) {
		this.strorgnrsdo = strorgnrsdo;
	}

	@Column(name = "strcmntro", length = 150)
	public String getStrcmntro() {
		return this.strcmntro;
	}

	public void setStrcmntro(String strcmntro) {
		this.strcmntro = strcmntro;
	}

	@Column(name = "strdrccn", length = 100)
	public String getStrdrccn() {
		return this.strdrccn;
	}

	public void setStrdrccn(String strdrccn) {
		this.strdrccn = strdrccn;
	}

	@Column(name = "numcntdd", precision = 20)
	public BigDecimal getNumcntdd() {
		return this.numcntdd;
	}

	public void setNumcntdd(BigDecimal numcntdd) {
		this.numcntdd = numcntdd;
	}

	@Column(name = "strprsntcn", length = 300)
	public String getStrprsntcn() {
		return this.strprsntcn;
	}

	public void setStrprsntcn(String strprsntcn) {
		this.strprsntcn = strprsntcn;
	}

	@Column(name = "booldnr")
	public Boolean getBooldnr() {
		return this.booldnr;
	}

	public void setBooldnr(Boolean booldnr) {
		this.booldnr = booldnr;
	}

	@Column(name = "numprco", precision = 20)
	public BigDecimal getNumprco() {
		return this.numprco;
	}

	public void setNumprco(BigDecimal numprco) {
		this.numprco = numprco;
	}

	@Column(name = "boolactvo")
	public Boolean getBoolactvo() {
		return this.boolactvo;
	}

	public void setBoolactvo(Boolean boolactvo) {
		this.boolactvo = boolactvo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datefchpblccn", length = 29)
	public Date getDatefchpblccn() {
		return this.datefchpblccn;
	}

	public void setDatefchpblccn(Date datefchpblccn) {
		this.datefchpblccn = datefchpblccn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "residuo")
	public Set<Calificacion> getCalificacions() {
		return this.calificacions;
	}

	public void setCalificacions(Set<Calificacion> calificacions) {
		this.calificacions = calificacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "residuo")
	public Set<FotoResiduo> getFotoResiduos() {
		return this.fotoResiduos;
	}

	public void setFotoResiduos(Set<FotoResiduo> fotoResiduos) {
		this.fotoResiduos = fotoResiduos;
	}

}
