package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SectorProductivo generated by hbm2java
 */
@Entity
@Table(name = "sector_productivo", schema = "public")
public class SectorProductivo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpksecpro;
	private String strnmbre;
	private Set<Tercero> terceros = new HashSet<Tercero>(0);

	public SectorProductivo() {
	}

	public SectorProductivo(int intpksecpro) {
		this.intpksecpro = intpksecpro;
	}

	public SectorProductivo(int intpksecpro, String strnmbre, Set<Tercero> terceros) {
		this.intpksecpro = intpksecpro;
		this.strnmbre = strnmbre;
		this.terceros = terceros;
	}

	@Id
	@SequenceGenerator(name = "sector_productivo_intpksecpro_seq", sequenceName = "public.sector_productivo_intpksecpro_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sector_productivo_intpksecpro_seq")
	@Column(name = "intpksecpro", unique = true, nullable = false)
	public int getIntpksecpro() {
		return this.intpksecpro;
	}

	public void setIntpksecpro(int intpksecpro) {
		this.intpksecpro = intpksecpro;
	}

	@Column(name = "strnmbre", length = 100)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sectorProductivo")
	public Set<Tercero> getTerceros() {
		return this.terceros;
	}

	public void setTerceros(Set<Tercero> terceros) {
		this.terceros = terceros;
	}

}
