package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Tercero generated by hbm2java
 */
@Entity
@Table(name = "tercero", schema = "public")
public class Tercero implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpkter;
	private SectorProductivo sectorProductivo;
	private TipoIdentificacion tipoIdentificacion;
	private Localidad localidad;
	private Perfil perfil;
	private Membresia membresia;
	private String strnmbre;
	private String straplldo;
	private Integer intidntfccn;
	private String strdrccn;
	private String strtlfno;
	private String strpgnwb;
	private String strcrrlctrnco;
	private String strcntrsna;
	private Integer intrptcn;
	private Boolean boolactvo;
	private Set<Aptitud> aptituds = new HashSet<Aptitud>(0);
	private Set<Buzon> buzonsForIntpkterpro = new HashSet<Buzon>(0);
	private Set<Educacion> educacions = new HashSet<Educacion>(0);
	private Set<Buzon> buzonsForIntpkteremp = new HashSet<Buzon>(0);
	private Set<Experiencia> experiencias = new HashSet<Experiencia>(0);
	private Set<Favorito> favoritos = new HashSet<Favorito>(0);
	private Set<Anuncio> anuncios = new HashSet<Anuncio>(0);
	private Set<Residuo> residuos = new HashSet<Residuo>(0);

	public Tercero() {
	}

	public Tercero(int intpkter) {
		this.intpkter = intpkter;
	}

	public Tercero(int intpkter, SectorProductivo sectorProductivo, TipoIdentificacion tipoIdentificacion, Localidad localidad, Perfil perfil,
			Membresia membresia, String strnmbre, String straplldo, Integer intidntfccn, String strdrccn, String strtlfno, String strpgnwb,
			String strcrrlctrnco, String strcntrsna, Integer intrptcn, Boolean boolactvo, Set<Aptitud> aptituds, Set<Buzon> buzonsForIntpkterpro,
			Set<Educacion> educacions, Set<Buzon> buzonsForIntpkteremp, Set<Experiencia> experiencias, Set<Favorito> favoritos,
			Set<Anuncio> anuncios, Set<Residuo> residuos) {
		this.intpkter = intpkter;
		this.sectorProductivo = sectorProductivo;
		this.tipoIdentificacion = tipoIdentificacion;
		this.localidad = localidad;
		this.perfil = perfil;
		this.membresia = membresia;
		this.strnmbre = strnmbre;
		this.straplldo = straplldo;
		this.intidntfccn = intidntfccn;
		this.strdrccn = strdrccn;
		this.strtlfno = strtlfno;
		this.strpgnwb = strpgnwb;
		this.strcrrlctrnco = strcrrlctrnco;
		this.strcntrsna = strcntrsna;
		this.intrptcn = intrptcn;
		this.boolactvo = boolactvo;
		this.aptituds = aptituds;
		this.buzonsForIntpkterpro = buzonsForIntpkterpro;
		this.educacions = educacions;
		this.buzonsForIntpkteremp = buzonsForIntpkteremp;
		this.experiencias = experiencias;
		this.favoritos = favoritos;
		this.anuncios = anuncios;
		this.residuos = residuos;
	}

	@Id
	@SequenceGenerator(name = "tercero_intpkter_seq", sequenceName = "public.tercero_intpkter_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tercero_intpkter_seq")
	@Column(name = "intpkter", unique = true, nullable = false)
	public int getIntpkter() {
		return this.intpkter;
	}

	public void setIntpkter(int intpkter) {
		this.intpkter = intpkter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpksecpro")
	public SectorProductivo getSectorProductivo() {
		return this.sectorProductivo;
	}

	public void setSectorProductivo(SectorProductivo sectorProductivo) {
		this.sectorProductivo = sectorProductivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkmem")
	public Membresia getMembresia() {
		return membresia;
	}

	public void setMembresia(Membresia membresia) {
		this.membresia = membresia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpktipide")
	public TipoIdentificacion getTipoIdentificacion() {
		return this.tipoIdentificacion;
	}

	public void setTipoIdentificacion(TipoIdentificacion tipoIdentificacion) {
		this.tipoIdentificacion = tipoIdentificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "strpkloc")
	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpkper")
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Column(name = "strnmbre", length = 100)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@Column(name = "straplldo", length = 100)
	public String getStraplldo() {
		return this.straplldo;
	}

	public void setStraplldo(String straplldo) {
		this.straplldo = straplldo;
	}

	@Column(name = "intidntfccn")
	public Integer getIntidntfccn() {
		return this.intidntfccn;
	}

	public void setIntidntfccn(Integer intidntfccn) {
		this.intidntfccn = intidntfccn;
	}

	@Column(name = "strdrccn", length = 100)
	public String getStrdrccn() {
		return this.strdrccn;
	}

	public void setStrdrccn(String strdrccn) {
		this.strdrccn = strdrccn;
	}

	@Column(name = "strtlfno", length = 50)
	public String getStrtlfno() {
		return strtlfno;
	}

	public void setStrtlfno(String strtlfno) {
		this.strtlfno = strtlfno;
	}

	@Column(name = "strpgnwb", length = 100)
	public String getStrpgnwb() {
		return this.strpgnwb;
	}

	public void setStrpgnwb(String strpgnwb) {
		this.strpgnwb = strpgnwb;
	}

	@Column(name = "strcrrlctrnco", length = 100)
	public String getStrcrrlctrnco() {
		return this.strcrrlctrnco;
	}

	public void setStrcrrlctrnco(String strcrrlctrnco) {
		this.strcrrlctrnco = strcrrlctrnco;
	}

	@Column(name = "strcntrsna", length = 100)
	public String getStrcntrsna() {
		return this.strcntrsna;
	}

	public void setStrcntrsna(String strcntrsna) {
		this.strcntrsna = strcntrsna;
	}

	@Column(name = "intrptcn")
	public Integer getIntrptcn() {
		return this.intrptcn;
	}

	public void setIntrptcn(Integer intrptcn) {
		this.intrptcn = intrptcn;
	}

	@Column(name = "boolactvo")
	public Boolean getBoolactvo() {
		return this.boolactvo;
	}

	public void setBoolactvo(Boolean boolactvo) {
		this.boolactvo = boolactvo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tercero")
	public Set<Aptitud> getAptituds() {
		return this.aptituds;
	}

	public void setAptituds(Set<Aptitud> aptituds) {
		this.aptituds = aptituds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "terceroByIntpkterpro")
	public Set<Buzon> getBuzonsForIntpkterpro() {
		return this.buzonsForIntpkterpro;
	}

	public void setBuzonsForIntpkterpro(Set<Buzon> buzonsForIntpkterpro) {
		this.buzonsForIntpkterpro = buzonsForIntpkterpro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tercero")
	public Set<Educacion> getEducacions() {
		return this.educacions;
	}

	public void setEducacions(Set<Educacion> educacions) {
		this.educacions = educacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "terceroByIntpkteremp")
	public Set<Buzon> getBuzonsForIntpkteremp() {
		return this.buzonsForIntpkteremp;
	}

	public void setBuzonsForIntpkteremp(Set<Buzon> buzonsForIntpkteremp) {
		this.buzonsForIntpkteremp = buzonsForIntpkteremp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tercero")
	public Set<Experiencia> getExperiencias() {
		return this.experiencias;
	}

	public void setExperiencias(Set<Experiencia> experiencias) {
		this.experiencias = experiencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tercero")
	public Set<Favorito> getFavoritos() {
		return this.favoritos;
	}

	public void setFavoritos(Set<Favorito> favoritos) {
		this.favoritos = favoritos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tercero")
	public Set<Anuncio> getAnuncios() {
		return this.anuncios;
	}

	public void setAnuncios(Set<Anuncio> anuncios) {
		this.anuncios = anuncios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tercero")
	public Set<Residuo> getResiduos() {
		return this.residuos;
	}

	public void setResiduos(Set<Residuo> residuos) {
		this.residuos = residuos;
	}

}
