package com.slack.ecotown.model;

// Generated 6/12/2017 11:05:32 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TipoMaterial generated by hbm2java
 */
@Entity
@Table(name = "tipo_material", schema = "public")
public class TipoMaterial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpktipmat;
	private String strnmbre;
	private Integer intcdgler;
	private String strdscrpcn;
	private String stricno;
	private String strdnsdd;
	private Integer intpntofsn;
	private BigDecimal numcndctvddtrmca;
	private BigDecimal numindcerfrccn;
	private String strprsn;
	private TipoMaterialGrupo tipoMaterialGrupo;
	private Set<Favorito> favoritos = new HashSet<Favorito>(0);
	private Set<Residuo> residuos = new HashSet<Residuo>(0);

	public TipoMaterial() {
	}

	public TipoMaterial(int intpktipmat) {
		this.intpktipmat = intpktipmat;
	}

	public TipoMaterial(int intpktipmat, String strnmbre, Integer intcdgler, String strdscrpcn, String stricno, String strdnsdd, Integer intpntofsn,
			BigDecimal numcndctvddtrmca, BigDecimal numindcerfrccn, String strprsn, TipoMaterialGrupo tipoMaterialGrupo, Set<Favorito> favoritos,
			Set<Residuo> residuos) {
		this.intpktipmat = intpktipmat;
		this.strnmbre = strnmbre;
		this.intcdgler = intcdgler;
		this.strdscrpcn = strdscrpcn;
		this.stricno = stricno;
		this.strdnsdd = strdnsdd;
		this.intpntofsn = intpntofsn;
		this.numcndctvddtrmca = numcndctvddtrmca;
		this.numindcerfrccn = numindcerfrccn;
		this.strprsn = strprsn;
		this.tipoMaterialGrupo = tipoMaterialGrupo;
		this.favoritos = favoritos;
		this.residuos = residuos;
	}

	@Id
	@SequenceGenerator(name = "tipo_material_intpktipmat_seq", sequenceName = "public.tipo_material_intpktipmat_seq", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tipo_material_intpktipmat_seq")
	@Column(name = "intpktipmat", unique = true, nullable = false)
	public int getIntpktipmat() {
		return this.intpktipmat;
	}

	public void setIntpktipmat(int intpktipmat) {
		this.intpktipmat = intpktipmat;
	}

	@Column(name = "strdnsdd", length = 50)
	public String getStrdnsdd() {
		return strdnsdd;
	}

	public void setStrdnsdd(String strdnsdd) {
		this.strdnsdd = strdnsdd;
	}

	@Column(name = "intpntofsn")
	public Integer getIntpntofsn() {
		return intpntofsn;
	}

	public void setIntpntofsn(Integer intpntofsn) {
		this.intpntofsn = intpntofsn;
	}

	@Column(name = "numcndctvddtrmca", precision = 6, scale = 2)
	public BigDecimal getNumcndctvddtrmca() {
		return numcndctvddtrmca;
	}

	public void setNumcndctvddtrmca(BigDecimal numcndctvddtrmca) {
		this.numcndctvddtrmca = numcndctvddtrmca;
	}

	@Column(name = "numindcerfrccn", precision = 6, scale = 2)
	public BigDecimal getNumindcerfrccn() {
		return numindcerfrccn;
	}

	public void setNumindcerfrccn(BigDecimal numindcerfrccn) {
		this.numindcerfrccn = numindcerfrccn;
	}

	@Column(name = "strprsn", length = 50)
	public String getStrprsn() {
		return strprsn;
	}

	public void setStrprsn(String strprsn) {
		this.strprsn = strprsn;
	}

	@Column(name = "strnmbre", length = 100)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@Column(name = "intcdgler")
	public Integer getIntcdgler() {
		return this.intcdgler;
	}

	public void setIntcdgler(Integer intcdgler) {
		this.intcdgler = intcdgler;
	}

	@Column(name = "strdscrpcn", length = 200)
	public String getStrdscrpcn() {
		return this.strdscrpcn;
	}

	public void setStrdscrpcn(String strdscrpcn) {
		this.strdscrpcn = strdscrpcn;
	}

	@Column(name = "stricno", length = 100)
	public String getStricno() {
		return stricno;
	}

	public void setStricno(String stricno) {
		this.stricno = stricno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intpktipmatgru")
	public TipoMaterialGrupo getTipoMaterialGrupo() {
		return tipoMaterialGrupo;
	}

	public void setTipoMaterialGrupo(TipoMaterialGrupo tipoMaterialGrupo) {
		this.tipoMaterialGrupo = tipoMaterialGrupo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMaterial")
	public Set<Favorito> getFavoritos() {
		return this.favoritos;
	}

	public void setFavoritos(Set<Favorito> favoritos) {
		this.favoritos = favoritos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMaterial")
	public Set<Residuo> getResiduos() {
		return this.residuos;
	}

	public void setResiduos(Set<Residuo> residuos) {
		this.residuos = residuos;
	}

}
