package com.slack.ecotown.model;

// Generated 29/12/2017 05:42:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoMedida generated by hbm2java
 */
@Entity
@Table(name = "tipo_medida", schema = "public")
public class TipoMedida implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intpktipmed;
	private String strnmbre;
	private String strsgls;

	public TipoMedida() {
	}

	public TipoMedida(int intpktipmed) {
		this.intpktipmed = intpktipmed;
	}

	public TipoMedida(int intpktipmed, String strnmbre, String strsgls) {
		this.intpktipmed = intpktipmed;
		this.strnmbre = strnmbre;
		this.strsgls = strsgls;
	}

	@Id
	@Column(name = "intpktipmed", unique = true, nullable = false)
	public int getIntpktipmed() {
		return this.intpktipmed;
	}

	public void setIntpktipmed(int intpktipmed) {
		this.intpktipmed = intpktipmed;
	}

	@Column(name = "strnmbre", length = 50)
	public String getStrnmbre() {
		return this.strnmbre;
	}

	public void setStrnmbre(String strnmbre) {
		this.strnmbre = strnmbre;
	}

	@Column(name = "strsgls", length = 50)
	public String getStrsgls() {
		return this.strsgls;
	}

	public void setStrsgls(String strsgls) {
		this.strsgls = strsgls;
	}

}
